### ISSUE TITLE
Local Commands

### ISSUE THREAD

**Issue by Wob76** [NovaGL/diy-melview#2]
Opening a new topic on this one.

I am interested in looking at the local commands you posted about, if only to speed up the responsiveness of commands sent to my unit, just want to clarify and try and expand on your comments.

You say
> If you are operating this over LAN you can also add the parameter "lc":1 this wil send commands immediately to the unit.

Does this mean that melview will issues the commands back to the unit faster, or does it rely on the "client" device to send the XML code you mention?

I have only done a couple of quick tests OFF\ON and the "LC KEY" seems to only change a little, have you done any extended testing of this, could you build a list of keys for each command to be used without talking to melview before each command, or do they change frequently?

Does the unit offer any sort of response to command, or is it a send and hope? I am assuming the mobile app uses this type of process to speed up commands when you are on your local network, also assuming that melview will still be polling the device and issue again if the local packet didn't make it for some reason?

Might call for some network packet sniffing.

**Comment by NovaGL** [comment]
It works like this.

When the LC1 is issued. It tells the service that you are in the local network.

It looks up the ip of the local unit from unitcapabilities.aspx 

It then does a XML POST to the that URL /smat
eg
http://192.168.1.1/smart

The LC KEY command is encoded, if you can work out the code structure it should be easy to issue local only commands. The only problem with that method is the response is also encoded meaning its hard to read the values back.

The response you will get back is something like this (might have been added in the latest API update)
```
<?xml version="1.0" encoding="utf-8"?>
<LSV>
	<MAC></MAC>
	<SERIAL></SERIAL>
	<CONNECT>ON</CONNECT>
	<STATUS>ERROR</STATUS>
	<PROFILECODE>
		<VALUE></VALUE>
		<VALUE></VALUE>
	</PROFILECODE>
	<DATDATE></DATDATE>
	<CODE>
		<VALUE></VALUE>
		<VALUE></VALUE>
		<VALUE></VALUE>
		<VALUE></VALUE>
		<VALUE></VALUE>
		<VALUE></VALUE>
	</CODE>
	<APP_VER>01.00</APP_VER>
	<WLAN_MAC_VER>3.4.3</WLAN_MAC_VER>
	<WEB_VER>01.00</WEB_VER>
	<SSL_LIMIT></SSL_LIMIT>
	<RSSI></RSSI>
</LSV>
```

**Comment by Wob76** [comment]
Cool, 

Thanks for the info, I might do some polling and collect the LC Key for various commands and see if they change over time or if they can be stored and used, Looking at the response it looks like there is at least some error codes, so it could be possible to use a local command "cache" and fall back to melview for a new code if an error is received.

I think it is worth exploring, thanks again for helping a newbie ;)

**Comment by NovaGL** [comment]
Ok so I have dug through what the lc command contains. I don't have everything as each model would be different, curious what you can dig up.

The numbering seems very confusing. I am sure it's encoded somehow I don't know though.

If you were game you could try to make up your own and send it direct.

EDIT: I thought I could decipherer it but some of the fields appear to be tricker to work out than others.
Here is roughly what I have worked out but might not be fully correct. 

ID | Position | Value
------------ | -------------|-------------
Unknown | 0-13 | This could be some kind of unit identifier all units seem to share the same numbers
Action Type | 14 | This is the action to be performed (1 - Power, 2 - Mode, 4 - Temp Change, 8 - Fan)
Unknown | 14-17| Zero padded
Power Type | 18| If power on this is 1 otherwise it's 0
Unknown | 19| Zero padded
Mode type| 20| 1 - HEAT, 3 COOL, 8 AUTO
Unknown | 21| Zero padded
Climate | 22 | d - increase, e - decrease
Climate| 23| Default 0 Manual control 1
Fan mode| 24| 5 - HIGH, 3 - MID, 2 - LOW
Unknown | 25-39| Zero padded
Unknown | 40| Field related to climate example value "a"
Unit Command | 41-45| Contains information such as temp level change

**Comment by Wob76** [comment]
Very interesting, I have issues commands and recorded the results, many of my commands to match up with yours, but I do have more action in the areas you have marked as padding, zones for example. I am on my laptop at the moment and a little hard to go through it all, I'll post my details in the next day or two.

A couple of interesting things to note, sending a command to the unit without talking to the melview does work, it does then cause a delay for that to appear on melview, probably similar to when I use the unit control.

If I include the LC:1 in my command to melview, but don't issue the local command to the unit, melview will still issue the command much the same as if I didn't include lc:1.

So I am considering 2 ways to approach local commands.
1. Operate much the same as the melview app, keep my code working as is, but just add a local command function, this would speed up the units response locally, drawback being we still have as much dependence on melview and hit it as often. 

2. Cache the LC:1 responses, and map those to commands, then if the cache contains a LC issue that locally, then only hit melview if there is a error when talking to the local hit, or if there is no corresponding LC key.

It does appear the keys are at least semi static, or linked to commands, but it will be interesting if they change at all over time, I guess as long as the error handling worked, that shouldn't be an issue. Either approach really shouldn't need the keys to be decoded or static.

**Comment by Wob76** [comment]
Just looking at the XML responses from the local unit, and it reports status normal even when a garbage command is issues, so handling local errors will be hard.

The code block also changes, can't see a reliable way, without a way to decode the code block, to identify an error when talking locally, so it might be safer to go with option 1, that way even if the local command does error, it will still update from melview much like it does now.

**Comment by Wob76** [comment]
Just going to leave this hear, it may help to look at decoding the CODE block the unit responds with, If the wifi unit is infact passing on the heat pumps commands.

I found it a few weeks ago, but just dawned on it may be related.

https://nicegear.co.nz/blog/hacking-a-mitsubishi-heat-pump-air-conditioner/

**Comment by NovaGL** [comment]
Thanks, looked into that interesting observations, but like I said it's beyond my knowledge and I don't want to break anything so I doubt I will use it.

I seems the LC value can contain multiple commands in one. But without decoding it, its really poking in the dark

**Comment by Wob76** [comment]
Not sure decoding the LC Key is going to be an easy task unless we get allot more people on board with a variety of units, but here are some of my results, I am just listing my noted differences, the rest match up with your results.

ID | Position | Value
-- | -- | --
Zone Action? | 11-12 | All commands except zone commands show "01" When I do a zone change I see "15"
Action | 14 | Adding to yours, during zone changes I see 1,2,4 and 8, depending on the zone I am changing, 1 and 2 match the zone number, but Zone2=4 and Zone8=8.

Zone Changes seem to overlap with other digits, I see a 1 or 0, on or off on 18 for Zone1, 20 for Zone2, 22 for Zone3 and 24 for Zone4.

Temps seem hard to decode, I forgot to not if I was going up or down in temp, just recorded the temp value, but I see changes in a number of bits. In bit 22 I see more than just "d" or "e" I have seen "c, b, a 9 and 8". Both 39 and 40 change for me, I see "a6, a8, aa, ac, and ae" I think these link back to the temp, being 19, 20, 21, 22 and 23. I am thinking the missing values in between would be for half degree values if you had it enabled.

41-42 seem like padding, I don't see anything in them.

23-44 change, but I can't pick a pattern.

**Comment by Wob76** [comment]
I have implemented the local command in my flow, just added it after my unitcommand.aspx. I take the response, pull out the LC Key and post it to the local unit.

As mentioned even with lc:1 in the command melview still updates my unit, so if there is an error it will just function as it has been, but this should at least speed up the local response most of the time. No way to error check the local unit as we can't decode it's response.

I'll do some testing at home tonight, I did some timing yesterday, and without this my button press to unit action was anywhere from a few seconds to about 30 seconds, and random. So I think melview talks to the unit every 30 seconds and the delay will be random depending on where in it's "cycle" you issue your command.

This is the flow, it reads payload.lc into a XML template, I have stored the units local ip is global.ac_localip and needed to pull that variable into the flow as I couldn't seem to use it in the URL value of the HTTP request node.

`[{"id":"d7bda16b.3e10a","type":"http request","z":"82cb19e.cee71e8","name":"Local Command","method":"POST","ret":"txt","url":"","tls":"","x":720,"y":340,"wires":[["398894ad.b1d36c"]]},{"id":"731eff10.7624d","type":"template","z":"82cb19e.cee71e8","name":"XML Payload","field":"payload","fieldType":"msg","format":"text","syntax":"mustache","template":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<CSV>\n\t<CONNECT>ON</CONNECT>\n\t<CODE>\n\t\t<VALUE>{{{payload.lc}}}</VALUE>\n\t</CODE>\n</CSV>","output":"str","x":390,"y":340,"wires":[["51d520de.e830c"]]},{"id":"398894ad.b1d36c","type":"debug","z":"82cb19e.cee71e8","name":"","active":true,"console":"false","complete":"false","x":890,"y":340,"wires":[]},{"id":"51d520de.e830c","type":"function","z":"82cb19e.cee71e8","name":"Define URL","func":"var url = \"http://\" + global.get(\"ac_localip\") + \"/smart\"\nmsg.url = url;\nreturn msg;","outputs":1,"noerr":0,"x":550,"y":340,"wires":[["d7bda16b.3e10a"]]}]`

**Comment by Wob76** [comment]
Ok, my testing this afternoon is very positive. With that flow addition my unit responds consistently in about 3 seconds to commands , including multiple consecutive commands.

**Comment by NovaGL** [comment]
So you just got local commands working now?

I have had it working for a long time. I just pass the local ip in the result so it passes it on directly every time

**Comment by Wob76** [comment]
Yeah, I had just been relying on melview to push the update. Much snapper response using the local command.

Ahh I'll have to take another look at the response payload, didn't realise the IP was in all repsonses, I was grabbing it from the unit capability command. Should simplify that part of my flow and remove a global variable :)

**Comment by NovaGL** [comment]
You're right it is in the unit capabilities but I just match the unitid to the ip.

If your ips are static you don't need to poll each time just keep a record of it.

**Comment by Wob76** [comment]
I only store the IP when's the flow first loads or if an error is thrown. I prefer to use a variable so if I do remap IPs I don't need to remember to modify the flow.

**Comment by andrewbaglin** [comment]
Hi,  could someone possibly post some example XML files so that I can have a play with this.
Thanks

**Comment by NovaGL** [comment]
Maybe @Wob76 

I don't for two reasons.
I don't want to brick your aircon if I give you a non-supported command. 
I don't want to send you commands that might have private keys to my device.

Try with Melview first then work on local commands.

**Comment by Wob76** [comment]
@andrewbaglin what XML are you referring to? XML to send to the unit or its XML responses?

I think as @NovaGL has said you are best to start with talking to Melview, the local commands are really an extension to that.

I have come to the conclusion that the local commands are a good extension to a Melview application, so as to speed up response times, but talking directly to the unit really needs some extensive testing across multiple units to make it reliable. By using Melview with it, if an error does occur with the local command, the unit will be updated via melview anyway.

You could happily "cache" the LC commands for a period of time to limit hits to Melview, or maybe just to use if Melview was unavailable. But until we can decode the units response, even if we can just work out when it has had an error, it is hard to know the local command has been successful.

I'll do some more testing in a week or so to test if my LC commands have changed at all, at this stage I am not sure if they are consistent over time or not.

**Comment by NovaGL** [comment]
In addition @andrewbaglin  different units operate differently.

If you don't know the basics of how MelView works things could go very wrong. I find Melview works great and is the prefered method.

That is why I don't go into detail on the readme

**Comment by gravypower** [comment]
So just wanted to post here if anyone else comes along and waists a evening trying to work this out. It seems that you can not send local commands to the MAC-558IF-E WiFi interface.

The app is just the a JS app, (I downloaded the APK file :) )
ex.js line 3444
` if (self.localControl == true && (self.adaptorType() == 'mac559' || self.adaptorType() == 'mac568')) { postdata.lc = 1; };`
